package com.gynlog.view.veiculo;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.gynlog.model.entity.Veiculo;
import com.gynlog.model.enums.MarcaDeCarro;
import com.gynlog.model.enums.StatusVeiculo;
import com.gynlog.view.TelaPrincipal;
import javax.swing.table.DefaultTableModel;

import javax.swing.JOptionPane;

import java.util.ArrayList;
import com.gynlog.controller.VeiculoController;

/**
 *
 * @author artur
 */
public class TelaVeiculo extends javax.swing.JFrame {

    VeiculoController cont = new VeiculoController();

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(TelaVeiculo.class.getName());

    private void carregarMarcas() {
        jComboBox_Marca.removeAllItems();
        jComboBox_Marca.addItem("SELECIONE");
        for (MarcaDeCarro marca : MarcaDeCarro.values()) {
            jComboBox_Marca.addItem(marca.name());
        }
    }

    /**
     * Creates new form Editar
     */
    public TelaVeiculo() {
        try {
            java.awt.Image icone = javax.imageio.ImageIO.read(getClass().getResource("/icons/logo-40x40.png"));
            this.setIconImage(icone);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        initComponents();

        carregarTabela();
        carregarMarcas();
        this.setLocationRelativeTo(null);
        jTextField_Id.setEnabled(false);
        jTextField_Ano.setEnabled(false);
        jTextField_Modelo.setEnabled(false);
        jTextField_Placa.setEnabled(false);
        jComboBox_Marca.setEnabled(false);
        jComboBox_Status.setEnabled(false);
        jComboBox_Filtro.setEnabled(false);
        jButton_Atualizar.setEnabled(false);
        jButton_Excluir.setEnabled(false);
        jButton_Adicionar.setEnabled(false);
        jButton_Buscar.setEnabled(false);

        // Detecta clique na linha da tabela
        jTable_Consulta_Tabela.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting()) {

                String escolha = jComboBox_Edicao.getSelectedItem().toString();

                if (escolha.equals("ATUALIZAR") || escolha.equals("EXCLUIR")) {
                    carregarCamposDaLinha();
                }
            }
        });

    }

    private void mostrarVeiculo(Veiculo veiculo) {

        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) jTable_Consulta_Tabela.getModel();

        model.setRowCount(0);

        if (veiculo != null) {

            model.addRow(new Object[]{
                veiculo.getIdVeiculo(),
                veiculo.getPlaca(),
                veiculo.getMarca(),
                veiculo.getModelo(),
                veiculo.getAnoDeFrabicacao(),
                veiculo.getStatusVeiculo()
            });
        }
    }

    private void limparTabela() {

        DefaultTableModel model
                = (DefaultTableModel) jTable_Consulta_Tabela.getModel();

        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jComboBox_Marca1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jComboBox_Edicao = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Consulta_Tabela = new javax.swing.JTable();
        jButtonVoltar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_Status = new javax.swing.JComboBox<>();
        jComboBox_Marca = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Placa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Modelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Ano = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Id = new javax.swing.JTextField();
        jButton_Atualizar = new javax.swing.JButton();
        jButton_Adicionar = new javax.swing.JButton();
        jButton_Excluir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_Filtro = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton_Buscar = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        jComboBox_Marca1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE:", "CHEVROLET", "FIAT", "VOLKSWAGEN", "HYUNDAI", "TOYOTA", "HONDA", "RENAULT", "NISSAN", "JEEP", "CITROËN", "PEUGEOT", "MITSUBISHI", "FORD", "KIA", "BYD" }));
        jComboBox_Marca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Marca1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Veiculo");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));

        jComboBox_Edicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE:", "ADICIONAR", "ATUALIZAR", "EXCLUIR", "FILTRO", "BUSCAR" }));
        jComboBox_Edicao.setToolTipText("SELECIONE:");
        jComboBox_Edicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_EdicaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ESCOLHA A OPÇÃO DESEJADA");

        jTable_Consulta_Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID VEICULO", "PLACA", "MARCA", "MODELO", "ANO DE FABRICAÇÃO", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Consulta_Tabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_Consulta_Tabela);
        if (jTable_Consulta_Tabela.getColumnModel().getColumnCount() > 0) {
            jTable_Consulta_Tabela.getColumnModel().getColumn(0).setResizable(false);
            jTable_Consulta_Tabela.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable_Consulta_Tabela.getColumnModel().getColumn(1).setResizable(false);
            jTable_Consulta_Tabela.getColumnModel().getColumn(2).setResizable(false);
            jTable_Consulta_Tabela.getColumnModel().getColumn(3).setResizable(false);
            jTable_Consulta_Tabela.getColumnModel().getColumn(4).setResizable(false);
            jTable_Consulta_Tabela.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable_Consulta_Tabela.getColumnModel().getColumn(5).setResizable(false);
        }

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("STATUS");

        jComboBox_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE:", "ATIVO", "INATIVO" }));

        jComboBox_Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE:", "CHEVROLET", "FIAT", "VOLKSWAGEN", "HYUNDAI", "TOYOTA", "HONDA", "RENAULT", "NISSAN", "JEEP", "CITROËN", "PEUGEOT", "MITSUBISHI", "FORD", "KIA", "BYD" }));
        jComboBox_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_MarcaActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MARCA");

        jTextField_Placa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Placa.setToolTipText("Placa");
        jTextField_Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PlacaActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PLACA");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MODELO");

        jTextField_Modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ModeloActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ANO");

        jTextField_Ano.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID VEICULO");

        jTextField_Id.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton_Atualizar.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Atualizar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_Atualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Atualizar.setText("ATUALIZAR");
        jButton_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AtualizarActionPerformed(evt);
            }
        });

        jButton_Adicionar.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Adicionar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_Adicionar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Adicionar.setText("ADICIONAR");
        jButton_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AdicionarActionPerformed(evt);
            }
        });

        jButton_Excluir.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Excluir.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_Excluir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Excluir.setText("EXCLUIR");
        jButton_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExcluirActionPerformed(evt);
            }
        });

        jLabel8.setText("...");
        jLabel8.setToolTipText("");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("icons/logo200x200.png"))); // NOI18N

        jComboBox_Filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE:", "MODELO", "MARCA", "ANO" }));
        jComboBox_Filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_FiltroActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("FILTRO");

        jButton_Buscar.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Buscar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_Buscar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Buscar.setText("Buscar");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(141, 141, 141))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_Modelo)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_Ano)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                        .addComponent(jComboBox_Edicao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(550, 550, 550))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_Edicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField_Id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox_Status)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Atualizar)
                            .addComponent(jButton_Adicionar)
                            .addComponent(jButton_Excluir)
                            .addComponent(jButton_Buscar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVoltar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_Marca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Marca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_Marca1ActionPerformed

    private void jComboBox_FiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_FiltroActionPerformed
        // TODO add your handling code here:
        try {
            if (jComboBox_Filtro.getSelectedIndex() == 0) {
                return;
            }

            String campo = jComboBox_Filtro.getSelectedItem().toString();
            ArrayList<Veiculo> lista = cont.filtro(campo);
            carregarTabela(lista);
            //limparCampos();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage()
            );

        }

    }//GEN-LAST:event_jComboBox_FiltroActionPerformed

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        // TODO add your handling code here:
        try {
            if (!jTextField_Placa.getText().trim().isEmpty()) {
                String placa = jTextField_Placa.getText();

                Veiculo veiculo = cont.buscarPorPlaca(placa);

                if (veiculo == null) {
                    JOptionPane.showMessageDialog(this, "Veiculo não encontrado");
                    return;
                }

                mostrarVeiculo(veiculo);
                limparCampos();
                return;
            }
            // Busca por marca
            if (jComboBox_Marca.getSelectedIndex() != 0) {

                MarcaDeCarro marca
                        = MarcaDeCarro.valueOf(
                                jComboBox_Marca.getSelectedItem().toString());

                ArrayList<Veiculo> lista
                        = cont.buscarPorMarca(marca);

                carregarTabela(lista);
                limparCampos();
                return;
            }

            // Busca por status
            if (jComboBox_Status.getSelectedIndex() != 0) {

                StatusVeiculo status
                        = StatusVeiculo.valueOf(
                                jComboBox_Status.getSelectedItem().toString());

                ArrayList<Veiculo> lista
                        = cont.buscarPorStatus(status);

                carregarTabela(lista);
                limparCampos();
                return;
            }

            JOptionPane.showMessageDialog(
                    this,
                    "Informe um critério de busca.");

        } catch (Exception erro) {

            JOptionPane.showMessageDialog(null, erro.getMessage());

        }
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jTextField_PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PlacaActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButton_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_AdicionarActionPerformed
        // TODO add your handling code here:
        try {

            String placa = jTextField_Placa.getText().toUpperCase();
            if (jComboBox_Marca.getSelectedIndex() == 0) {
                throw new Exception("Selecione uma marca.");
            }
            MarcaDeCarro marca = MarcaDeCarro.valueOf(jComboBox_Marca.getSelectedItem().toString());

            // int id = Integer.parseInt(jTextField_Id.getText());
            String modelo = jTextField_Modelo.getText().toUpperCase();
            int anoDeFabricacao = Integer.parseInt(jTextField_Ano.getText());
            StatusVeiculo status = StatusVeiculo.valueOf(jComboBox_Status.getSelectedItem().toString());

            Veiculo tipoDeVeiculo = new Veiculo();
            tipoDeVeiculo.setPlaca(placa);
            tipoDeVeiculo.setMarca(marca);
            tipoDeVeiculo.setModelo(modelo);
            tipoDeVeiculo.setAnoDeFrabicacao(anoDeFabricacao);
            tipoDeVeiculo.setStatusVeiculo(status);

            VeiculoController cont = new VeiculoController();
            cont.adicionarVeiculo(tipoDeVeiculo);
            carregarTabela();
            limparCampos();

            JOptionPane.showMessageDialog(this, "Veiculo adicionado com sucesso!");
            carregarTabela();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }// GEN-LAST:event_jButton_AdicionarActionPerformed

    private void jButton_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_ExcluirActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jTextField_Id.getText());

            cont.removerVeiculo(id);
            carregarTabela();
            limparCampos();
            JOptionPane.showMessageDialog(null, "Item excluido com sucesso!");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }// GEN-LAST:event_jButton_ExcluirActionPerformed

    private void jButton_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_AtualizarActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jTextField_Id.getText());
            String placa = jTextField_Placa.getText().toUpperCase();
            MarcaDeCarro marca = MarcaDeCarro.valueOf(jComboBox_Marca.getSelectedItem().toString());
            String modelo = jTextField_Modelo.getText().toUpperCase();
            int ano = Integer.parseInt(jTextField_Ano.getText());
            StatusVeiculo status = StatusVeiculo.valueOf(jComboBox_Status.getSelectedItem().toString());

            Veiculo objAtualizado = new Veiculo(
                    id, placa, marca, modelo, ano, status);

            cont.atualizarVeiculo(objAtualizado);
            carregarTabela();
            limparCampos();

            JOptionPane.showMessageDialog(null, "Veículo atualizado com sucesso!");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }// GEN-LAST:event_jButton_AtualizarActionPerformed

    private void jTextField_ModeloActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_ModeloActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField_ModeloActionPerformed

    private void jComboBox_EdicaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox_EdicaoActionPerformed
        // TODO add your handling code here:
        String escolha = (String) jComboBox_Edicao.getSelectedItem();
        if (escolha.equals("ATUALIZAR")) {

            jTextField_Id.setEnabled(false);
            jTextField_Placa.setEnabled(true);
            jTextField_Modelo.setEnabled(true);
            jTextField_Ano.setEnabled(true);
            jComboBox_Marca.setEnabled(true);
            jComboBox_Status.setEnabled(true);
            jComboBox_Filtro.setEnabled(false);
            jButton_Buscar.setEnabled(false);

            jButton_Atualizar.setEnabled(true);
            jButton_Excluir.setEnabled(false);
            jButton_Adicionar.setEnabled(false);
            limparCampos();

        } else if (escolha.equals("EXCLUIR")) {

            // Só o ID deve ser
            jTextField_Id.setEnabled(true);
            jTextField_Placa.setEnabled(true);
            jTextField_Modelo.setEnabled(true);
            jTextField_Ano.setEnabled(true);
            jComboBox_Marca.setEnabled(true);
            jComboBox_Status.setEnabled(true);
            jComboBox_Filtro.setEnabled(false);
            jButton_Buscar.setEnabled(false);

            jButton_Atualizar.setEnabled(false);
            jButton_Excluir.setEnabled(true);
            jButton_Adicionar.setEnabled(false);
            limparCampos();

        } else if (escolha.equals("ADICIONAR")) {
            jTextField_Id.setEnabled(false);
            jTextField_Placa.setEnabled(true);
            jTextField_Modelo.setEnabled(true);
            jTextField_Ano.setEnabled(true);
            jComboBox_Marca.setEnabled(true);
            jComboBox_Status.setEnabled(true);
            jComboBox_Filtro.setEnabled(false);
            jButton_Buscar.setEnabled(false);

            jButton_Adicionar.setEnabled(true);
            jButton_Atualizar.setEnabled(false);
            jButton_Excluir.setEnabled(false);
            limparCampos();

        } else if (escolha.equals("FILTRO")) {
            jTextField_Id.setEnabled(false);
            jTextField_Placa.setEnabled(false);
            jTextField_Modelo.setEnabled(false);
            jTextField_Ano.setEnabled(false);
            jComboBox_Marca.setEnabled(false);
            jComboBox_Status.setEnabled(false);
            jComboBox_Filtro.setEnabled(true);
            jButton_Buscar.setEnabled(false);

            jButton_Adicionar.setEnabled(false);
            jButton_Atualizar.setEnabled(false);
            jButton_Excluir.setEnabled(false);
            limparCampos();

        } else if (escolha.equals("BUSCAR")) {
            limparTabela();
            jTextField_Id.setEnabled(false);
            jTextField_Placa.setEnabled(true);
            jTextField_Modelo.setEnabled(true);
            jTextField_Ano.setEnabled(true);
            jComboBox_Marca.setEnabled(true);
            jComboBox_Status.setEnabled(true);
            jComboBox_Filtro.setEnabled(false);
            jButton_Buscar.setEnabled(true);

            jButton_Adicionar.setEnabled(false);
            jButton_Atualizar.setEnabled(false);
            jButton_Excluir.setEnabled(false);
            limparCampos();

        } else {

            jTextField_Id.setEnabled(false);
            jTextField_Placa.setEnabled(false);
            jTextField_Modelo.setEnabled(false);
            jTextField_Ano.setEnabled(false);
            jComboBox_Marca.setEnabled(false);
            jComboBox_Status.setEnabled(false);
            jComboBox_Filtro.setEnabled(false);

            jButton_Atualizar.setEnabled(false);
            jButton_Excluir.setEnabled(false);

        }
    }// GEN-LAST:event_jComboBox_EdicaoActionPerformed

    private void jComboBox_MarcaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox_MarcaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBox_MarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    private void carregarTabela() {
        try {
            // Pega o modelo da tabela
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable_Consulta_Tabela
                    .getModel();
            model.setRowCount(0); // limpa a tabela

            // Chama o DAO para pegar a lista de veículos
            VeiculoController cont = new VeiculoController();
            ArrayList<Veiculo> lista = cont.listar();

            // Adiciona na JTable
            for (Veiculo v : lista) {
                model.addRow(new Object[]{
                    v.getIdVeiculo(),
                    v.getPlaca(),
                    v.getMarca(),
                    v.getModelo(),
                    v.getAnoDeFrabicacao(),
                    v.getStatusVeiculo()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar tabela: " + e.getMessage());
        }
    }

    private void carregarTabela(ArrayList<Veiculo> lista) {

        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) jTable_Consulta_Tabela.getModel();

        model.setRowCount(0);

        for (Veiculo v : lista) {

            model.addRow(new Object[]{
                v.getIdVeiculo(),
                v.getPlaca(),
                v.getMarca(),
                v.getModelo(),
                v.getAnoDeFrabicacao(),
                v.getStatusVeiculo()
            });
        }
    }

    private void carregarCamposDaLinha() {
        int linha = jTable_Consulta_Tabela.getSelectedRow();

        if (linha == -1) {
            return; // Nenhuma linha selecionada
        }

        jTextField_Id.setText(jTable_Consulta_Tabela.getValueAt(linha, 0).toString());
        jTextField_Placa.setText(jTable_Consulta_Tabela.getValueAt(linha, 1).toString());
        jComboBox_Marca.setSelectedItem(jTable_Consulta_Tabela.getValueAt(linha, 2));
        jTextField_Modelo.setText(jTable_Consulta_Tabela.getValueAt(linha, 3).toString());
        jTextField_Ano.setText(jTable_Consulta_Tabela.getValueAt(linha, 4).toString());
        jComboBox_Status.setSelectedItem(jTable_Consulta_Tabela.getValueAt(linha, 5).toString());
    }

    private void limparCampos() {
        jTextField_Id.setText("");
        jTextField_Placa.setText("");
        jTextField_Modelo.setText("");
        jTextField_Ano.setText("");
        jComboBox_Marca.setSelectedIndex(0); // volta para "SELECIONE:"
        jComboBox_Status.setSelectedIndex(0);// volta para "SELECIONE:"
        jComboBox_Filtro.setSelectedIndex(0);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaVeiculo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JButton jButton_Adicionar;
    private javax.swing.JButton jButton_Atualizar;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Excluir;
    private javax.swing.JComboBox<String> jComboBox_Edicao;
    private javax.swing.JComboBox<String> jComboBox_Filtro;
    private javax.swing.JComboBox<String> jComboBox_Marca;
    private javax.swing.JComboBox<String> jComboBox_Marca1;
    private javax.swing.JComboBox<String> jComboBox_Status;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Consulta_Tabela;
    private javax.swing.JTextField jTextField_Ano;
    private javax.swing.JTextField jTextField_Id;
    private javax.swing.JTextField jTextField_Modelo;
    private javax.swing.JTextField jTextField_Placa;
    // End of variables declaration//GEN-END:variables
}
